### PR TITLE
chore: archive go-libp2p-webrtc-direct

### PR DESCRIPTION
**Pull request by p-shahi**
### Summary
Archive said repo

### Why do you need this?
For reasons mentioned in this comment: https://github.com/libp2p/go-libp2p-webrtc-direct/issues/53#issuecomment-1306160381

### What else do we need to know?
cc: @backkem who is listed as the lead maintainer of the repo

**DRI:** myself

### Reviewer's Checklist

- [ ] It is clear where the request is coming from (if unsure, ask)
- [ ] All the automated checks passed
- [ ] The YAML changes reflect the summary of the request
- [ ] The Terraform plan posted as a comment reflects the summary of the request

### CODE REVIEW

**Review by BigLep — APPROVED** [review]
The change itself looks good to me, but I'd like to see an archival notice at the top of https://github.com/libp2p/go-libp2p-webrtc-direct#readme that points someone to why it's deprecated and what is coming along to replace it.

**Comment by galargh** [comment]
> The change itself looks good to me, but I'd like to see an archival notice at the top of https://github.com/libp2p/go-libp2p-webrtc-direct#readme that points someone to why it's deprecated and what is coming along to replace it.

Idea for the future: it'd be cool to be able to prepare it inline in a PR like this one and let the automation stick it on top of the README before archiving it.

**Review by backkem — APPROVED** [review]

**Comment by backkem** [comment]
Happy to see the official implementation maturing. Great work 👌

**Review by mxinden — APPROVED** [review]
No objections from my end.

**Comment by BigLep** [comment]
Per above, I'm good to merge.  Lets also add a clear notification at the top of the repo.

# ⚠️⚠️⚠️⚠️⚠️⚠️
Status: Archived and not maintained
Alternatives: link
Questions: ask in the repo above
# ⚠️⚠️⚠️⚠️⚠️⚠️

or something like this

**Pull request merged**
