### PR TITLE
Adjust org owners/admins

### PR DESCRIPTION
**Pull request by BigLep**
### Summary
This aligns with the "reduce org owners" step listed in https://github.com/ipfs/ipfs/issues/511.

This is the first step of wider 2024Q1 permissions cleanup.

### Why do you need this?
Github org safety.  See https://github.com/ipfs/ipfs/issues/511 for more info.

### Timeline
- [x] 2024-02-12: public PR
- [x] 2024-02-12: notify affected parties: https://github.com/libp2p/github-mgmt/pull/202#issuecomment-1939203875
- [ ] 2024-02-16: merge this change assuming no major pushback
- [x] 2024-02-16: @galargh give "github-mgmt stewards" team "[moderator](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#organization-moderators)" and "[security manager](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#security-managers)" roles

### Reviewer's Checklist

- [x] It is clear where the request is coming from (if unsure, ask)
- [x] All the automated checks passed
- [x] The YAML changes reflect the summary of the request
- [x] The Terraform plan posted as a comment reflects the summary of the request

### CODE REVIEW

**Comment by BigLep** [comment]
@aschmahmann
@daviddias
@jacobheun
@jbenet
@marten-seemann
@momack2
@whyrusleeping

I'm @mentioning you to inform you that your libp2p github "org ownership" permissions are being removed as part of a https://github.com/ipfs/ipfs/issues/511. You are still a member of the libp2p github org and retain your existing direct github repo permissions or team permissions.

The current plan is to merge this change on Wednesday, 2024-02-14.

That said, this isn't a one-way door. If we got this wrong or you see the notification after the fact, a new PR can be created fix permissions.

Thanks and let me know if you have any questions or concerns.

**Comment by BigLep** [comment]
@p-shahi : FYI I have added you as an org owner given the TPM role you play across the project.

**Review by p-shahi — APPROVED** [review]

**Comment by BigLep** [comment]
I updated the PR to account for cleaning up the github-mgmt stewards team.

**Review by mxinden — APPROVED** [review]
Thanks for the ping. I am in favor of the change!

**Comment by momack2** [comment]
Thanks @BigLep ! I'm fine on being removed - but probably makes sense for @jbenet to stay an owner given his continued libp2p involvement

**Comment by BigLep** [comment]
@momack2:

> Thanks @BigLep ! I'm fine on being removed - but probably makes sense for @jbenet to stay an owner given his continued libp2p involvement

Let's have the conversation about what to do with foundational-but-not-currently-active-in-github people like Juan in the similar IPFS PR: https://github.com/ipfs/github-mgmt/pull/189#issuecomment-1942874694 .  I'm game for whatever is decided.

(I can't pull up Juan's libp2p github activity the last 6 months at https://github.com/organizations/libp2p/settings/audit-log?q=actor%3Ajbenet+ because I'm not an org owner 😄)

**Comment by BigLep** [comment]
I'll leave this open until 2024-02-15 before merging.

I updated the messaging to be more clear as well:

> I'm @mentioning you to inform you that your libp2p github "org ownership" permissions will be removed as part of a https://github.com/ipfs/ipfs/issues/511 unless you respond back with your use-case for having these broad permissions by 2024-02-14. You will still be a member of the libp2p github org, retain your existing direct github repo permissions or team permissions, and be able to make permission requests through https://github.com/lilbp2p/github-mgmt.

**Review by galargh — APPROVED** [review]

**Comment by BigLep** [comment]
Based on https://github.com/ipfs/ipfs/issues/511#issuecomment-1947577416, I did more changes here to reduce the only true org owners to @galargh and @andyschwab-admin.

Here is the summary:

Org members who are no longer org-admins and are not in the "github-mgmt stewards" team (thus a true reduction of permissions):
- @aschmahmann
- @daviddias
- @jacobheun
- @jbenet
- @marten-seemann
- @momack2
- @whyrusleeping

Org members who are no longer org-admins but are still in the "github-mgmt stewards" team (thus can still get to "org owner" mode if needed):
- @p-shahi 🆕
- @raulk 🆕
- @Stebalien 🆕

Org members who were on the "github-mgmt stewards" team but have been removed (thus have had a reduction in permissions):
- @BigLep 
- @MarcoPolo 🆕 - I did this since there are already two IP Shipyard representatives)
- @mxinden
- @willscott

🆕 indicates changes as of 2024-02-15

There are comments in the PR explaining more about the decision-making.  Feedback welcome.  I am shooting to be able to merge this on Friday, 2024-02-16.  (I will personally be away on leave for a while starting 2024-02-17, but others like @galargh and @p-shahi can certainly engage here if we can't wrap this up by then.)

**Comment by BigLep** [comment]
I'm merging, given we've had time on this to iterate and fine-tune, @lidel support for this kind of approach for IPFS in https://github.com/ipfs/ipfs/issues/511#issuecomment-1948560571, that we're in a better place than we were before, and knowing further changes can be done in a followup if needed. (A phase 2 to this 2024Q1 permissions cleanup will likely start happening week of 2024-02-19 per https://github.com/ipfs/ipfs/issues/511.)

**Pull request merged**
