### PR TITLE
Add dharmapunk82 and karolkozlowski to the bifrost team

### PR DESCRIPTION
**Pull request by mcamou**

### CODE REVIEW

**Comment by mcamou** [comment]
I am confused as to why this is making changes unrelated to what I've done in the PR (e.g. removing `hsanjuan` from the `Bifrost` team).

**Comment by galargh** [comment]
Hey, sorry about that. It's unlucky timing, I'm in the middle of fixing a synchronization issue and your plans got caught up in that. I'll make sure this PR is in the correct state afterwards. Sorry for the inconvenience.

**Comment by galargh** [comment]
I expect to be ready to review and merge this in about 20 minutes if that's alright with you.

**Review by galargh — APPROVED** [review]
All looks good now :) Sorry for the mixups

**Comment by galargh** [comment]
@dharmapunk82, @karolkozlowski could you accept the invites to the org? They should be waiting for you in your email inboxes :)

**Pull request merged**
