### PR TITLE
chore: add p-shahi to Repos Go & JS and Shipyard

### PR DESCRIPTION
**Pull request by p-shahi**
### Summary
Push access to Repos Go and JS

Follow up to https://github.com/libp2p/github-mgmt/pull/245

**DRI:** myself

### Reviewer's Checklist

- [ ] It is clear where the request is coming from (if unsure, ask)
- [ ] All the automated checks passed
- [ ] The YAML changes reflect the summary of the request
- [ ] The Terraform plan posted as a comment reflects the summary of the request

### CODE REVIEW

**Comment by aschmahmann** [comment]
@p-shahi could you restore the original formatting, there's a bunch of whitespace changes added to the PR.

Otherwise for the practical aspects LGTM

**Comment by p-shahi** [comment]
@aschmahmann that's VScode removing trailing whitespaces. Would you like me to remove those?

**Comment by aschmahmann** [comment]
I don't feel strongly. Only looking on my phone right now so can't tell what kind of whitespace changes (e.g. doing ones that'll just show up again when someone on a different OS or with a different IDE does the next PR would be bad, but if it's just a cleanup then 👍).

**Comment by p-shahi** [comment]
Yes its a cleanup! I need your stamp before I can merge.

**Review by aschmahmann — APPROVED** [review]

**Comment by aschmahmann** [comment]
Unfortunately I can't help you as my permissions were removed here (Marco also has no permissions). cc @libp2p/github-mgmt-stewards who do have permissions

**Pull request merged**
