### PR TITLE
Add hsanjuan to Admin / w3dt-stewards

### PR DESCRIPTION
**Pull request by hsanjuan**
* I am not new and more involved in libp2p stuff than some current admins
* Maintainer of some repos
* To reduce friction, I need the liberty to be able to contribute across the board, request reviews, push branches. I shouldn't be fighting permission issues.
* I used to be able to do this anyways.

### CODE REVIEW

**Review by lidel — APPROVED** [review]
Let's merge this and #33 to unblock @hsanjuan  (he is already Admin in https://github.com/ipfs/github-mgmt/blob/master/github/ipfs.yml)

Q: @galargh is there a long term plan to remove people from `admin` group?

**Comment by galargh** [comment]
Could you remove yourself from `members.member` list? It's here: https://github.com/libp2p/github-mgmt/blob/0ebc419a7a2425ac071185c2d50736038a7fe3be/github/libp2p.yml#L66 Apparently, the setup is perfectly happy about there being duplicate entries between `members.admin` and `members.member` but, as you can see in the posted plan, it chose to leave your role in the org as `member`. At the very least, we should be getting a clearer error about this - I created an issue to track this https://github.com/protocol/github-mgmt-template/issues/50.

> Q: @galargh is there a long term plan to remove people from admin group?

I'd say that yes, this is the general direction we want to move in. There's no a written plan for it yet though. 

@hsanjuan does the fix of repository-team relationship for `go-libp2p-relay-daemon` resolve the issue you had? Is there anything org-admin permission allows that you found yourself needing lately? I'm trying to understand what setup would work best here.

> To reduce friction, I need the liberty to be able to contribute across the board, request reviews, push branches. I shouldn't be fighting permission issues.

These requirements should be satisfied by `push` access everywhere.

Ideally, I'd like to be able to automatically assign teams to repos on creation. That would help us avoid situations like the one with `go-libp2p-relay-daemon`.

As for the `w3dt-stewards` membership, my thinking is that it should reflect the org-chart team membership. So if there's anything this team can do that should be extended to a broader group, I think we might need a new team.

**Comment by hsanjuan** [comment]
> These requirements should be satisfied by push access everywhere

If you promise me that that is going to be the case. The friction comes from that not being the case ie. in relay-daemon.

**Comment by hsanjuan** [comment]
But yeah, the concrete issue is fixed.

**Comment by galargh** [comment]
> > These requirements should be satisfied by push access everywhere
> 
> If you promise me that that is going to be the case. The friction comes from that not being the case ie. in relay-daemon.

I think https://github.com/libp2p/github-mgmt/issues/34 (Automate granting access to all go repos for the Go repos team) is the most important step in ensuring that's the case. We're going to try to prioritise delivering it.

BTW, I have nothing against making you an admin either. I really just wanted to understand the circumstances better so that we can make more informed decision going forward.

**Pull request closed without merging**
